### ISSUE TITLE
Screenshot includes portal details.

### ISSUE THREAD

**Issue by Ir1d** [nibogd/ingress-ice#117]
![ice-2018-03-25--08-45-21](https://user-images.githubusercontent.com/10709657/37870449-05b7f674-3009-11e8-8633-7524de375e2c.png)

```
area=https://www.ingress.com/intel?ll=34.616363,112.417002&z=14
delay=3000
minlevel=8
maxlevel=8
width=1366
height=768
iitc=false
```

It's weird and I'm not quite sure what caused this.
Every single image in the screenshots/ folder includes portal details like this.

**Comment by nibogd** [comment]
Hey!
Sorry for a long delay. I've opened your link and saw that in browser the filters are disabled, because your zoom is too low. So you can only see links (all links, no way to filter by portal level) and this is the Ingress limitation.

I tested the level selector with a zoom ratio where the level chooser is available. So please just don't use the level selector (leave the default 1 and 8 values for minlevel and maxlevel respectively) when it isn't available on the ingress map.

Anyway, thanks for the report! I think I should throw a warning and not use the selector when it's unavailable. But, when I have time.

**Comment by Ir1d** [comment]
Thx for the response, but I've got another question. I wonder why the portal detail section was activated(the green box shown in the screenshot).
Really Thx for your answer, though i didn't ask, It confused me a lot XD.

**Comment by Ir1d** [comment]
Solved by this:
```
#> Inject IITC? (true/false)
iitc=true
# plugins=["https://static.iitc.me/build/release/plugins/link-show-direction.user.js"]
plugins=["https://static.iitc.me/build/release/plugins/fix-googlemap-china-offset.user.js"]
```
