### ISSUE TITLE
Don't store Google account login in plain text

### ISSUE THREAD

**Issue by mxxcon** [nibogd/ingress-ice#19]
It's a little bit worrying to have my Google login info saved in plain text.

Can you somehow utilize oauth-style login similar to the way https://github.com/nylonee/hangupsbot does it?
It just gives me a URL to go to which returns a long string to paste back into hangupsbot. That hangupsbot never sees my raw login credentials.

**Comment by nibogd** [comment]
I read all Google OAuth documentation but haven't found a way to do something like this :disappointed: 

It's all because Ingress Intel map is an AppEngine application which doesn't allow logging in via OAuth, it uses OAuth itself. The only thing you can do is to use command-line arguments with phantomJS and no config files, as written [here](https://github.com/nibogd/ingress-ice/wiki/Config-file-format).
```
./phantomjs ice.js $VERSION $EMAIL $PASSWD $LINK $MIN_LEVEL $MAX_LEVEL $DELAY $WIDTH $HEIGHT $FOLDER $NUMBER $IITC $TIMESTAMP
```
which will look like 
```
./phantomjs ice.js 1 some-email "This$is&my*passwd" "https://www.ingress.com/intel?ll=52.98348,5.071092&z=3" 8 8 300 4096 2160 /home/link/ice/ 0 0 0
```

**Comment by SniperRus** [comment]
Or use sacsid  (session id) and csrf token (ingress Intel timelaps from
github)

пт, 19 Июн 2015, 22:46, Nikita-kun <notifications@github.com>:

**Comment by nibogd** [comment]
Finally done this (as @SniperRus suggested — using cookies).

**Comment by mxxcon** [comment]
Thank you! :smile:
