### ISSUE TITLE
Grab messages

### ISSUE THREAD

**Issue by sasha2002** [nibogd/ingress-ice#60]
Can you make it to grab entire chats and portals data, and write it to some database or file?

**Comment by nibogd** [comment]
Hm... I'm afraid it's a bad idea. Capturing the chat is impossible without
IITC and it's prohibited by ToS, Niantic would ban all ice users because it
would be like a guardian tracker. AFAIK you can't collect portals data with
PhantomJS, but the messages in the chat contain latitude, longitude, name,
faction and owner.

чт, 19 нояб. 2015 г. в 3:24, sasha2002 <notifications@github.com>:

**Comment by sasha2002** [comment]
Ok, i understand.
But if we just collect chat data?

**Comment by adostes** [comment]
I agree with @nibogd , it's a terrible idea.

**Comment by nibogd** [comment]
@sasha2002 Sorry, but no. That could be used for guardian hunting :(

чт, 19 нояб. 2015 г. в 18:51, adostes <notifications@github.com>:

**Comment by c2nprds** [comment]
@sasha2002 That deviate from the philosophy of the ingress-ice.

**Comment by ozero** [comment]
Open IITC FAQ page and read the answer for "Can you add an export feature?". It describes why export feature is bad idea.
http://iitc.jonatkins.com/?page=faq#export

**Comment by nibogd** [comment]
@ozero , @c2nprds , you are right, thank you. Closing the issue.
