### ISSUE TITLE
IITC Injection no longer works after MapQuest update

### ISSUE THREAD

**Issue by RocketJumpingOtter** [nibogd/ingress-ice#94]
![ice-2016-07-31--13-28-03](https://cloud.githubusercontent.com/assets/7952127/17278444/4139db4c-5723-11e6-9f2e-e1d78b57b588.png)

**Comment by nibogd** [comment]
Thank you for the report! I hope that IITC will update once fixing this issue.
Now you can add this to your config ([details](https://github.com/nibogd/ingress-ice/wiki/Loading-IITC-plugins)):
```
pluginsConfig=[{"key":"plugin-linkshowdirection-mode","value":"Static near origin"},{"key":"iitc-base-map","value":"Google Roads"}]
```
instead of `pluginsConfig=[{"key":"plugin-linkshowdirection-mode","value":"Static near origin"},{"key":"YourKeyHere","value":""}]`
And it should use the Google Roads map (you can insert any map name there).

Please, report back if it works, I'll add it to the next release.

**Comment by jbouse** [comment]
Only update I'd see IITC making is to remove MapQuest and set a new default. Not sure how high of a priority the IITC dev team will set to make a new release just for that. I already changed the `iitc-base-map` as suggested to be my personal default so I don't have this issue myself.

**Comment by nibogd** [comment]
@jbouse oh, then i must release v4.4.1 with this fix.
Will be done, thanks.
