### ISSUE TITLE
Multiple locations

### ISSUE THREAD

**Issue by imthejavi** [nibogd/ingress-ice#96]
It is possible to capture different locations with the single account? and how to do that if it is possible 👍 

Cheers from ENL Mexico.

**Comment by nibogd** [comment]
Hi! This is impossible inside a single instance of ingress-ice due to its architecture, but you may launch several instances.

If you use Windows:
1. Make several copies of your ingress-ice directory
2. Copy your configuration (or get the sample from `ingress-ice/ice/ingress-ice.conf.sample`) into `ingress-ice.conf` file in the root of each directory
3. Edit each file according to your needs, place different location links there
4. Launch all ingress-ices
(this is briefly described in README.md)

If you use Linux, then launch ingress-ice with -i option each time (e.g. `./ingress-ice -i park.conf`). It will create and use different configurations. Run `./ingress-ice -h` for other options.

Cheers
